chore: remove main branch protection

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,9 +4,9 @@
 protected_branch="main"
 current_branch=$(git symbolic-ref --short HEAD 2>/dev/null)
 
-if [ "$current_branch" == "$protected_branch" ]; then
-  echo "Error: Commits directly to the '$protected_branch' branch are not allowed."
-  exit 1
-fi
+# if [ "$current_branch" == "$protected_branch" ]; then
+#   echo "Error: Commits directly to the '$protected_branch' branch are not allowed."
+#   exit 1
+# fi
 
 npx lint-staged --concurrent false --relative
